name: Build

on:
  workflow_call:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [web] # TODO: Add android, ios, linux, macos, windows.
    steps:
      # Set up Flutter.
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # flutter-version: '' TODO: Pin this to a version.
          channel: stable

      - run: flutter pub get

      - name: Checkout
        uses: actions/checkout@v3

      - run: flutter doctor -v

      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - run: flutter build ${{ matrix.target }}

      - name: Run tests
        run: flutter test --dart-define=FLUTTER_TEST=true
