name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/_build.yml 

  publish_private:
    uses: ./.github/workflows/_docker_publish.yml
    needs: [build]
    secrets: inherit
    with:
      remote-docker-image: "us-central1-docker.pkg.dev/topl-shared-project-dev/topl-artifacts-dev/annulus"
